"""add clan ban fields

Revision ID: 06ad7c089bde
Revises: 5c0573d620ad
Create Date: 2026-06-16 23:40:18.446452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06ad7c089bde'
down_revision: Union[str, Sequence[str], None] = '5c0573d620ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clans', sa.Column('is_banned', sa.Boolean(), nullable=True))
    op.add_column('clans', sa.Column('ban_reason', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clans', 'ban_reason')
    op.drop_column('clans', 'is_banned')
    # ### end Alembic commands ###
