"""Add marketplace models

Revision ID: 22c8edb38e73
Revises: 42acf3282d0d
Create Date: 2026-06-04 10:36:20.644762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22c8edb38e73'
down_revision: Union[str, Sequence[str], None] = '42acf3282d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_items_id'), 'store_items', ['id'], unique=False)
    op.create_index(op.f('ix_store_items_name'), 'store_items', ['name'], unique=False)
    op.create_table('battlepass_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battlepass_seasons_id'), 'battlepass_seasons', ['id'], unique=False)
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('price_paid', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['store_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchases_id'), 'purchases', ['id'], unique=False)
    op.create_table('battlepass_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bp_season_id', sa.Integer(), nullable=True),
    sa.Column('current_xp', sa.Integer(), nullable=True),
    sa.Column('is_premium_unlocked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['bp_season_id'], ['battlepass_seasons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battlepass_progress_id'), 'battlepass_progress', ['id'], unique=False)
    op.create_table('battlepass_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bp_season_id', sa.Integer(), nullable=True),
    sa.Column('tier_level', sa.Integer(), nullable=True),
    sa.Column('required_xp', sa.Integer(), nullable=True),
    sa.Column('reward_name', sa.String(length=255), nullable=True),
    sa.Column('reward_type', sa.String(length=50), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['bp_season_id'], ['battlepass_seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battlepass_tiers_id'), 'battlepass_tiers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_battlepass_tiers_id'), table_name='battlepass_tiers')
    op.drop_table('battlepass_tiers')
    op.drop_index(op.f('ix_battlepass_progress_id'), table_name='battlepass_progress')
    op.drop_table('battlepass_progress')
    op.drop_index(op.f('ix_purchases_id'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_battlepass_seasons_id'), table_name='battlepass_seasons')
    op.drop_table('battlepass_seasons')
    op.drop_index(op.f('ix_store_items_name'), table_name='store_items')
    op.drop_index(op.f('ix_store_items_id'), table_name='store_items')
    op.drop_table('store_items')
    # ### end Alembic commands ###
