"""Add squad tournaments

Revision ID: 5c0573d620ad
Revises: 7b538ae46623
Create Date: 2026-06-16 14:50:52.671551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c0573d620ad'
down_revision: Union[str, Sequence[str], None] = '7b538ae46623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('winner_team_id', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('team1_id', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('team2_id', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('team1_score', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('team2_score', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'matches', 'teams', ['winner_team_id'], ['id'])
    op.create_foreign_key(None, 'matches', 'teams', ['team1_id'], ['id'])
    op.create_foreign_key(None, 'matches', 'teams', ['team2_id'], ['id'])
    op.add_column('registrations', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'registrations', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.drop_column('registrations', 'team_id')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_column('matches', 'team2_score')
    op.drop_column('matches', 'team1_score')
    op.drop_column('matches', 'team2_id')
    op.drop_column('matches', 'team1_id')
    op.drop_column('matches', 'winner_team_id')
    # ### end Alembic commands ###
