"""Add eSports Career System

Revision ID: 74f6d47aabb5
Revises: 1879bd3f2d40
Create Date: 2026-06-08 14:12:56.845079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74f6d47aabb5'
down_revision: Union[str, Sequence[str], None] = '1879bd3f2d40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified_pro', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('pro_badge_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pro_badge_url')
    op.drop_column('users', 'is_verified_pro')
    # ### end Alembic commands ###
