"""rename_stripe_to_upi

Revision ID: 7ce983454397
Revises: 74f6d47aabb5
Create Date: 2026-06-15 17:48:06.972318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ce983454397'
down_revision: Union[str, Sequence[str], None] = '74f6d47aabb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('payout_upi_id', sa.String(length=255), nullable=True))
    op.drop_column('users', 'stripe_account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_account_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'payout_upi_id')
    # ### end Alembic commands ###
