"""Add clan models

Revision ID: 9c5269b5d56e
Revises: 458c11a0d3ce
Create Date: 2026-06-03 10:46:07.635515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c5269b5d56e'
down_revision: Union[str, Sequence[str], None] = '458c11a0d3ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('tag', sa.String(length=10), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('leader_id', sa.Integer(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_recruiting', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['leader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clans_id'), 'clans', ['id'], unique=False)
    op.create_index(op.f('ix_clans_name'), 'clans', ['name'], unique=True)
    op.create_index(op.f('ix_clans_tag'), 'clans', ['tag'], unique=True)
    op.create_table('clan_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clan_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('achieved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clan_id'], ['clans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clan_achievements_id'), 'clan_achievements', ['id'], unique=False)
    op.create_table('clan_join_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clan_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clan_id'], ['clans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clan_join_requests_id'), 'clan_join_requests', ['id'], unique=False)
    op.create_table('clan_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clan_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clan_id'], ['clans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clan_members_id'), 'clan_members', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clan_members_id'), table_name='clan_members')
    op.drop_table('clan_members')
    op.drop_index(op.f('ix_clan_join_requests_id'), table_name='clan_join_requests')
    op.drop_table('clan_join_requests')
    op.drop_index(op.f('ix_clan_achievements_id'), table_name='clan_achievements')
    op.drop_table('clan_achievements')
    op.drop_index(op.f('ix_clans_tag'), table_name='clans')
    op.drop_index(op.f('ix_clans_name'), table_name='clans')
    op.drop_index(op.f('ix_clans_id'), table_name='clans')
    op.drop_table('clans')
    # ### end Alembic commands ###
