"""Add fantasy budget

Revision ID: 9d2f36948645
Revises: 06ad7c089bde
Create Date: 2026-06-17 10:55:58.707770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d2f36948645'
down_revision: Union[str, Sequence[str], None] = '06ad7c089bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fantasy_teams', sa.Column('budget_remaining', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fantasy_teams', 'budget_remaining')
    # ### end Alembic commands ###
