"""Add lobby models

Revision ID: aa44d3d1f8d8
Revises: 22c8edb38e73
Create Date: 2026-06-05 11:37:43.734953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa44d3d1f8d8'
down_revision: Union[str, Sequence[str], None] = '22c8edb38e73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('inviter_id', sa.Integer(), nullable=True),
    sa.Column('invitee_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_invites_id'), 'team_invites', ['id'], unique=False)
    op.create_table('team_join_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_join_requests_id'), 'team_join_requests', ['id'], unique=False)
    op.add_column('teams', sa.Column('is_recruiting', sa.Boolean(), nullable=True))
    op.add_column('teams', sa.Column('max_members', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'max_members')
    op.drop_column('teams', 'is_recruiting')
    op.drop_index(op.f('ix_team_join_requests_id'), table_name='team_join_requests')
    op.drop_table('team_join_requests')
    op.drop_index(op.f('ix_team_invites_id'), table_name='team_invites')
    op.drop_table('team_invites')
    # ### end Alembic commands ###
